spring.datasource.url=jdbc:mysql://localhost:3306/venuevista
spring.datasource.username=root
spring.datasource.password=Pprg1234@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081